(()=>{const W=window.WORDS,$=x=>document.querySelector(x),mix=a=>[...a].sort(()=>Math.random()-.5);
let saved={};try{saved=JSON.parse(localStorage.getItem("djhs2000")||"{}")}catch(e){}
const state=new Map(W.map(x=>{const s=Object.assign({r:0,w:0,due:0,status:"新字",skill:{}},saved[x.w]||{});s.skill=Object.assign({word:{r:0,w:0},meaning:{r:0,w:0},listen:{r:0,w:0},context:{r:0,w:0}},s.skill||{});["word","meaning","listen","context"].forEach(k=>s.skill[k]=Object.assign({r:0,w:0},s.skill[k]||{}));return[x.w,s]}));
let score=0,combo=0,turn=0,cur,mode,left,timer,locked=false,track=localStorage.getItem("djhs2000-track")||"auto";
function setTrack(v){clearInterval(timer);track=v;localStorage.setItem("djhs2000-track",v);document.querySelectorAll(".trackbtn").forEach(b=>b.classList.toggle("active",b.dataset.track===v));const notes={auto:"自動適性｜依目前答題表現動態調整題池；答得穩會逐步加入較難字。",core:"基礎 1200｜1,200 字打底題池，適合先建立基本字彙量。",full:"完整 2000｜2,055 筆國中常用候選字詞，適合全面練習。",gept:"GEPT 初級｜目前以較常用的 1,600 字作進階練習，官方初級標記持續核對。"};$("#tracknote").textContent=notes[v];show()}
function persist(){const o={};state.forEach((v,k)=>o[k]=v);localStorage.setItem("djhs2000",JSON.stringify(o))}
function stats(){$("#score").textContent=score;$("#combo").textContent=combo;const P=pool(),known=P.filter(x=>{const s=state.get(x.w);return s.status==="已熟悉"||s.status==="已掌握"}).length;$("#known").textContent=known;const pct=P.length?Math.round(known/P.length*100):0;const pe=$("#progressText"),pf=$("#progressFill");if(pe)pe.textContent=known+" / "+P.length+"（"+pct+"%）";if(pf)pf.style.width=pct+"%"}
function speak(text){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.82;speechSynthesis.speak(u)}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null;
function normSpeech(s){return (s||"").toLowerCase().replace(/[^a-z' ]/g," ").replace(/\s+/g," ").trim()}
function shadow(target,isSentence=false){const out=$("#shadowResult");if(!SR){out.className="shadowresult retry";out.textContent="這個瀏覽器目前不支援語音辨識，可先使用「聽發音」跟讀。";return}if(recognition){try{recognition.abort()}catch(e){}}recognition=new SR();recognition.lang="en-US";recognition.interimResults=false;recognition.maxAlternatives=3;const btn=isSentence?$("#shadowSentence"):$("#shadowWord");btn.classList.add("listening");btn.textContent="正在聽…";out.className="shadowresult";out.textContent="請開始說英文";recognition.onresult=e=>{const heard=[...e.results[0]].map(x=>x.transcript);const t=normSpeech(target);const best=heard.find(x=>normSpeech(x)===t)||heard[0]||"";const exact=heard.some(x=>normSpeech(x)===t);let ok=exact;if(isSentence&&!ok){const tw=t.split(" ").filter(Boolean),hw=normSpeech(best).split(" ").filter(Boolean);const hit=tw.filter(x=>hw.includes(x)).length;ok=tw.length>0&&hit/tw.length>=.8}const tw=t.split(" ").filter(Boolean),hw=normSpeech(best).split(" ").filter(Boolean);let hit=tw.filter(x=>hw.includes(x)).length;let match=isSentence?Math.round(hit/Math.max(1,tw.length)*100):(exact?100:(normSpeech(best).includes(t)||t.includes(normSpeech(best))?70:30));const praise=match>=90?"Excellent!":match>=75?"Good!":"Keep going!";const grade=match>=90?"great":match>=75?"good":"try";out.className="shadowresult scored "+(ok?"ok":"retry");out.innerHTML=`<div class="scorebadge ${grade}"><strong>${match}</strong><span>辨識完成度</span></div><div class="scorelabel ${grade}">${praise}</div><div class="scoreheard">${ok?"✓ 辨識成功":"我聽到："+best}</div>${match>=75?`<div class="stars">${Array.from({length:7},(_,i)=>`<i class="star" style="left:${42+(i%3)*8}%;top:${42+(i%2)*10}%;--x:${(i-3)*28}px;--y:${-45-Math.abs(i-3)*12}px">★</i>`).join("")}</div>`:""}`;btn.classList.remove("listening");btn.textContent=isSentence?"挑戰整句":"跟讀單字"};recognition.onerror=e=>{out.className="shadowresult retry";out.textContent=e.error==="not-allowed"?"需要允許麥克風權限才能跟讀。":"沒有辨識到，請再試一次。";btn.classList.remove("listening");btn.textContent=isSentence?"挑戰整句":"跟讀單字"};recognition.onend=()=>{btn.classList.remove("listening");btn.textContent=isSentence?"挑戰整句":"跟讀單字"};try{recognition.start()}catch(e){out.className="shadowresult retry";out.textContent="麥克風暫時無法啟動，請再試一次。"}}
function pool(){const ranked=[...W].sort((a,b)=>(a.difficulty-b.difficulty)||(a.w.length-b.w.length));if(track==="core")return ranked.slice(0,1200);if(track==="gept")return ranked.filter(x=>x.difficulty<=4).slice(0,1600);if(track==="auto"){const recent=[...state.values()].reduce((o,s)=>{o.a+=s.r+s.w;o.c+=s.r;return o},{a:0,c:0}),rate=recent.a?recent.c/recent.a:.5;let n=1200;if(recent.a>=20&&rate>=.72)n=1600;if(recent.a>=50&&rate>=.82)n=W.length;if(recent.a>=20&&rate<.55)n=900;return ranked.slice(0,n)}return W}
function pick(){const P=pool();let due=P.filter(x=>state.get(x.w).due<=turn),weak=due.filter(x=>state.get(x.w).status==="待加強");if(weak.length&&Math.random()<.75)return mix(weak)[0];let fresh=due.filter(x=>state.get(x.w).status==="新字");if(fresh.length)return mix(fresh)[0];return mix(due.length?due:P)[0]}
function clock(){clearInterval(timer);left=mode==="context"?13:10;paint();timer=setInterval(()=>{left-=.1;paint();if(left<=0)fail(true)},100)}
function paint(){left=Math.max(0,left);const t=$("#time"),b=$("#bar"),card=$(".card");t.textContent=left.toFixed(1);t.classList.toggle("urgent",left<=4);t.classList.toggle("time-warn",left<=7&&left>4);t.classList.toggle("time-danger",left<=4);t.classList.toggle("time-critical",left<=2&&left>0);b.classList.toggle("time-warn",left<=7&&left>4);b.classList.toggle("time-danger",left<=4&&left>0);b.classList.toggle("time-critical",left<=2&&left>0);card.classList.toggle("time-panic",left<=4&&left>2);card.classList.toggle("time-critical",left<=2&&left>0);const total=mode==="context"?13:10;b.style.width=(left/total*100)+"%"}
function editDist(a,b){a=(a||"").toLowerCase();b=(b||"").toLowerCase();const d=Array.from({length:a.length+1},()=>Array(b.length+1).fill(0));for(let i=0;i<=a.length;i++)d[i][0]=i;for(let j=0;j<=b.length;j++)d[0][j]=j;for(let i=1;i<=a.length;i++)for(let j=1;j<=b.length;j++)d[i][j]=Math.min(d[i-1][j]+1,d[i][j-1]+1,d[i-1][j-1]+(a[i-1]===b[j-1]?0:1));return d[a.length][b.length]}
function zhTokens(s){return new Set((s||"").replace(/[，、；。\s]/g,"").split("").filter(x=>x.trim()))}
function distractScore(x,field){if(field==="w"){const dist=editDist(cur.w,x.w),len=Math.max(cur.w.length,x.w.length),shape=1-dist/Math.max(1,len),sameLen=1-Math.min(1,Math.abs(cur.w.length-x.w.length)/6),samePos=cur.p&&x.p&&cur.p===x.p?1:0;return shape*5+sameLen*2+samePos*2+Math.random()*.8}const a=zhTokens(cur.z),b=zhTokens(x.z);let overlap=0;a.forEach(t=>{if(b.has(t))overlap++});const semantic=overlap/Math.max(1,Math.min(a.size,b.size)),samePos=cur.p&&x.p&&cur.p===x.p?1:0,sameDiff=1-Math.min(1,Math.abs((cur.difficulty||3)-(x.difficulty||3))/4);return semantic*5+samePos*3+sameDiff*1.5+Math.random()*.8}
function cleanZh(s){return(s||"").replace(/[（）()\[\]，、；。,.!！?？\s]/g,"")}
function ambiguous(x,field){if(field==="w"){const a=(cur.w||"").toLowerCase(),b=(x.w||"").toLowerCase();return a===b}const a=cleanZh(cur.z),b=cleanZh(x.z);if(!a||!b)return true;if(a===b)return true;if(a.length>=2&&b.length>=2&&(a.includes(b)||b.includes(a)))return true;const A=zhTokens(cur.z),B=zhTokens(x.z);let hit=0;A.forEach(t=>{if(B.has(t))hit++});return hit>=2&&hit/Math.max(1,Math.min(A.size,B.size))>=.8}
function opts(field){const P=pool(),base=P.filter(x=>x.w!==cur.w&&x[field]&&x[field]!==cur[field]),safe=base.filter(x=>!ambiguous(x,field));let ranked=safe.map(x=>({x,s:distractScore(x,field)})).sort((a,b)=>b.s-a.s);const chosen=[],labels=new Set([cur[field]]);for(const o of ranked){if(labels.has(o.x[field]))continue;chosen.push(o.x);labels.add(o.x[field]);if(chosen.length===3)break}if(chosen.length<3)for(const x of mix(base)){if(labels.has(x[field])||ambiguous(x,field))continue;chosen.push(x);labels.add(x[field]);if(chosen.length===3)break}if(chosen.length<3)for(const x of mix(base)){if(labels.has(x[field]))continue;chosen.push(x);labels.add(x[field]);if(chosen.length===3)break}return mix([cur,...chosen]).map(x=>({x,label:x[field]}))}
function contextOK(x){const e=(x.e||"").trim(),w=(x.w||"").trim();if(!e||!w)return false;const low=e.toLowerCase(),target=w.toLowerCase();if(low.split(target).length-1!==1)return false;if(e.length<18||e.length>150)return false;const blank=low.replace(target,"_____");const words=blank.split(/\s+/).filter(Boolean).length;if(words<4)return false;if(blank.trim().endsWith("_____")&&words<6)return false;return true}
function chooseMode(s){const modes=["en","zh","listen","context"].filter(m=>m!=="context"||contextOK(cur));if(track==="auto"){const scoreMode=m=>{const k=m==="listen"?"listen":m==="context"?"context":m==="zh"?"word":"meaning",q=s.skill[k];return(q.w*3)-(q.r*.7)+(q.r+q.w===0?1.5:0)+Math.random()*1.2};return modes.sort((a,b)=>scoreMode(b)-scoreMode(a))[0]}if(s.w>0&&contextOK(cur)&&Math.random()<.6)return"context";return Math.random()<.18?"listen":Math.random()<.36?"zh":"en"}
function show(){turn++;locked=false;cur=pick();const s=state.get(cur.w);$("#level").textContent=s.status;$("#feedback").textContent="";$("#example").style.display="none";$("#next").style.display="none";const sr=$("#shadowResult");if(sr){sr.textContent="";sr.className="shadowresult"};mode=chooseMode(s);let os;
if(mode==="listen"){$("#mode").textContent="聽力選字";$("#speak").style.visibility="visible";$("#prompt").textContent="🔊";$("#prompt").style.fontSize="46px";$("#pos").textContent="聽發音，選出你聽到的英文單字";os=opts("w");setTimeout(()=>speak(cur.w),250)}
else if(mode==="context"){$("#mode").textContent="例句填空";$("#speak").style.visibility="hidden";$("#prompt").textContent=cur.e.replace(new RegExp(cur.w,"i"),"_____");$("#prompt").style.fontSize="26px";$("#pos").textContent="選出最適合的單字";os=opts("w")}
else if(mode==="zh"){$("#mode").textContent="中翻英";$("#speak").style.visibility="hidden";$("#prompt").textContent=cur.z;$("#prompt").style.fontSize="46px";$("#pos").textContent=cur.p;os=opts("w")}
else{$("#mode").textContent="英翻中";$("#speak").style.visibility="visible";$("#prompt").textContent=cur.w;$("#prompt").style.fontSize="46px";$("#pos").textContent=cur.p;os=opts("z");setTimeout(()=>speak(cur.w),250)}
const c=$("#choices");c.innerHTML="";os.forEach(o=>{let b=document.createElement("button");b.textContent=o.label;b.onclick=()=>answer(o.x);c.appendChild(b)});stats();clock()}
function skillKey(){return mode==="listen"?"listen":mode==="context"?"context":mode==="zh"?"word":"meaning"}
function update(ok,to=false){const s=state.get(cur.w),k=skillKey(),q=s.skill[k];if(ok){q.r++;q.w=Math.max(0,q.w-1)}else{q.w++;q.r=Math.max(0,q.r-1)};if(ok){s.r++;s.w=Math.max(0,s.w-1);s.status=s.r>=4?"已掌握":s.r>=2?"已熟悉":"學習中";s.due=turn+(s.r>=4?14:s.r>=2?7:4)}else{s.w++;s.r=Math.max(0,s.r-1);s.status="待加強";s.due=turn+(s.w>=2?1:to?3:2)}persist()}
function skillSummary(){const s=state.get(cur.w),f=k=>{const q=s.skill[k];return q.r>=3&&q.w===0?"✓":q.w>q.r?"△":"•"};return "能力｜認字 "+f("word")+"　理解 "+f("meaning")+"　聽力 "+f("listen")+"　語境 "+f("context")}
function reveal(msg){$("#speak").style.visibility="visible";$("#feedback").textContent=msg+"　"+skillSummary();$("#answer").textContent=cur.w+" "+cur.p+"｜"+cur.z;$("#sentence").innerHTML=cur.e.replace(new RegExp("("+cur.w+")","ig"),"<strong>$1</strong>");$("#translation").textContent=cur.t;$("#example").style.display="block";$("#next").style.display="block"}
function answer(x){if(locked)return;locked=true;clearInterval(timer);[...$("#choices").children].forEach(b=>b.disabled=true);if(x.w===cur.w){combo++;let bonus=Math.round(left*10);score+=100+bonus+(combo-1)*20;update(true);$(".card").classList.remove("wrongflash");$(".card").classList.add("rightflash");setTimeout(()=>$(".card").classList.remove("rightflash"),500);reveal("答對！速度加分 +"+bonus+(combo>=3?"・"+combo+" 連擊":""))}else{combo=0;update(false);$(".card").classList.remove("rightflash");$(".card").classList.add("wrongflash");setTimeout(()=>$(".card").classList.remove("wrongflash"),450);reveal("答錯。正確答案："+cur.w+"｜"+cur.z)}stats()}
function fail(to){if(locked)return;locked=true;clearInterval(timer);combo=0;update(false,to);[...$("#choices").children].forEach(b=>b.disabled=true);reveal("時間到。正確答案："+cur.w+"｜"+cur.z);stats()}
const helpDialog=$("#helpDialog");$("#help").onclick=()=>helpDialog.showModal();$("#helpClose").onclick=()=>helpDialog.close();helpDialog.onclick=e=>{if(e.target===helpDialog)helpDialog.close()};
const welcome=$("#welcome");if(!localStorage.getItem("djhs2000-welcome-seen"))welcome.style.display="flex";$("#dismissWelcome").onclick=()=>{localStorage.setItem("djhs2000-welcome-seen","1");welcome.style.display="none"};document.querySelectorAll(".trackbtn").forEach(b=>{b.addEventListener("click",e=>{e.preventDefault();setTrack(b.dataset.track)})});document.querySelectorAll(".trackbtn").forEach(b=>b.classList.toggle("active",b.dataset.track===track));const tn={auto:"自動適性｜依目前答題表現動態調整題池；答得穩會逐步加入較難字。",core:"基礎 1200｜1,200 字打底題池，適合先建立基本字彙量。",full:"完整 2000｜2,055 筆國中常用候選字詞，適合全面練習。",gept:"GEPT 初級｜目前以較常用的 1,600 字作進階練習，官方初級標記持續核對。"};$("#tracknote").textContent=tn[track];$("#next").onclick=show;$("#speak").onclick=()=>{if(!locked&&mode!=="en"&&mode!=="listen")return;speak(cur.w)};$("#speakSentence").onclick=()=>speak(cur.e);$("#shadowWord").onclick=()=>shadow(cur.w,false);$("#shadowSentence").onclick=()=>shadow(cur.e,true);if(!SR){$("#shadowWord").title="此瀏覽器不支援語音辨識";$("#shadowSentence").title="此瀏覽器不支援語音辨識"}$("#reset").onclick=()=>{if(confirm("確定要清除這台裝置的學習進度嗎？")){localStorage.removeItem("djhs2000");location.reload()}};show()})();