(()=>{const W=window.WORDS,$=x=>document.querySelector(x),mix=a=>[...a].sort(()=>Math.random()-.5);
let saved={};try{saved=JSON.parse(localStorage.getItem("djhs2000")||"{}")}catch(e){}
const state=new Map(W.map(x=>[x.w,Object.assign({r:0,w:0,due:0,status:"新字"},saved[x.w]||{})]));
let score=0,combo=0,turn=0,cur,mode,left,timer,locked=false,track=localStorage.getItem("djhs2000-track")||"auto";
function setTrack(v){clearInterval(timer);track=v;localStorage.setItem("djhs2000-track",v);document.querySelectorAll(".trackbtn").forEach(b=>b.classList.toggle("active",b.dataset.track===v));const notes={auto:"自動適性｜依目前答題表現動態調整題池；答得穩會逐步加入較難字。",core:"基礎 1200｜1,200 字打底題池，適合先建立基本字彙量。",full:"完整 2000｜2,055 筆國中常用候選字詞，適合全面練習。",gept:"GEPT 初級｜目前以較常用的 1,600 字作進階練習，官方初級標記持續核對。"};$("#tracknote").textContent=notes[v];show()}
function persist(){const o={};state.forEach((v,k)=>o[k]=v);localStorage.setItem("djhs2000",JSON.stringify(o))}
function stats(){$("#score").textContent=score;$("#combo").textContent=combo;const P=pool(),known=P.filter(x=>{const s=state.get(x.w);return s.status==="已熟悉"||s.status==="已掌握"}).length;$("#known").textContent=known;const pct=P.length?Math.round(known/P.length*100):0;const pe=$("#progressText"),pf=$("#progressFill");if(pe)pe.textContent=known+" / "+P.length+"（"+pct+"%）";if(pf)pf.style.width=pct+"%"}
function speak(text){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang="en-US";u.rate=.82;speechSynthesis.speak(u)}
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null;
function normSpeech(s){return (s||"").toLowerCase().replace(/[^a-z' ]/g," ").replace(/\s+/g," ").trim()}
function shadow(target,isSentence=false){const out=$("#shadowResult");if(!SR){out.className="shadowresult retry";out.textContent="這個瀏覽器目前不支援語音辨識，可先使用「聽發音」跟讀。";return}if(recognition){try{recognition.abort()}catch(e){}}recognition=new SR();recognition.lang="en-US";recognition.interimResults=false;recognition.maxAlternatives=3;const btn=isSentence?$("#shadowSentence"):$("#shadowWord");btn.classList.add("listening");btn.textContent="正在聽…";out.className="shadowresult";out.textContent="請開始說英文";recognition.onresult=e=>{const heard=[...e.results[0]].map(x=>x.transcript);const t=normSpeech(target);const best=heard.find(x=>normSpeech(x)===t)||heard[0]||"";const exact=heard.some(x=>normSpeech(x)===t);let ok=exact;if(isSentence&&!ok){const tw=t.split(" ").filter(Boolean),hw=normSpeech(best).split(" ").filter(Boolean);const hit=tw.filter(x=>hw.includes(x)).length;ok=tw.length>0&&hit/tw.length>=.8}out.className="shadowresult "+(ok?"ok":"retry");out.textContent=(ok?"✓ 辨識成功｜":"再試一次｜我聽到：")+best;btn.classList.remove("listening");btn.textContent=isSentence?"挑戰整句":"跟讀單字"};recognition.onerror=e=>{out.className="shadowresult retry";out.textContent=e.error==="not-allowed"?"需要允許麥克風權限才能跟讀。":"沒有辨識到，請再試一次。";btn.classList.remove("listening");btn.textContent=isSentence?"挑戰整句":"跟讀單字"};recognition.onend=()=>{btn.classList.remove("listening");btn.textContent=isSentence?"挑戰整句":"跟讀單字"};try{recognition.start()}catch(e){out.className="shadowresult retry";out.textContent="麥克風暫時無法啟動，請再試一次。"}}
function pool(){const ranked=[...W].sort((a,b)=>(a.difficulty-b.difficulty)||(a.w.length-b.w.length));if(track==="core")return ranked.slice(0,1200);if(track==="gept")return ranked.filter(x=>x.difficulty<=4).slice(0,1600);if(track==="auto"){const recent=[...state.values()].reduce((o,s)=>{o.a+=s.r+s.w;o.c+=s.r;return o},{a:0,c:0}),rate=recent.a?recent.c/recent.a:.5;let n=1200;if(recent.a>=20&&rate>=.72)n=1600;if(recent.a>=50&&rate>=.82)n=W.length;if(recent.a>=20&&rate<.55)n=900;return ranked.slice(0,n)}return W}
function pick(){const P=pool();let due=P.filter(x=>state.get(x.w).due<=turn),weak=due.filter(x=>state.get(x.w).status==="待加強");if(weak.length&&Math.random()<.75)return mix(weak)[0];let fresh=due.filter(x=>state.get(x.w).status==="新字");if(fresh.length)return mix(fresh)[0];return mix(due.length?due:P)[0]}
function clock(){clearInterval(timer);left=10;paint();timer=setInterval(()=>{left-=.1;paint();if(left<=0)fail(true)},100)}
function paint(){left=Math.max(0,left);$("#time").textContent=left.toFixed(1);$("#time").classList.toggle("urgent",left<=3);$("#bar").style.width=(left*10)+"%"}
function opts(field){const P=pool();return mix([cur,...mix(P.filter(x=>x.w!==cur.w)).slice(0,3)]).map(x=>({x,label:x[field]}))}
function show(){turn++;locked=false;cur=pick();const s=state.get(cur.w);$("#level").textContent=s.status;$("#feedback").textContent="";$("#example").style.display="none";$("#next").style.display="none";const sr=$("#shadowResult");if(sr){sr.textContent="";sr.className="shadowresult"};mode=s.w>0&&Math.random()<.6?"context":Math.random()<.18?"listen":Math.random()<.36?"zh":"en";let os;
if(mode==="listen"){$("#mode").textContent="聽力選字";$("#speak").style.visibility="visible";$("#prompt").textContent="🔊";$("#prompt").style.fontSize="46px";$("#pos").textContent="聽發音，選出你聽到的英文單字";os=opts("w");setTimeout(()=>speak(cur.w),250)}
else if(mode==="context"){$("#mode").textContent="例句填空";$("#speak").style.visibility="hidden";$("#prompt").textContent=cur.e.replace(new RegExp(cur.w,"i"),"_____");$("#prompt").style.fontSize="26px";$("#pos").textContent="選出最適合的單字";os=opts("w")}
else if(mode==="zh"){$("#mode").textContent="中翻英";$("#speak").style.visibility="hidden";$("#prompt").textContent=cur.z;$("#prompt").style.fontSize="46px";$("#pos").textContent=cur.p;os=opts("w")}
else{$("#mode").textContent="英翻中";$("#speak").style.visibility="visible";$("#prompt").textContent=cur.w;$("#prompt").style.fontSize="46px";$("#pos").textContent=cur.p;os=opts("z");setTimeout(()=>speak(cur.w),250)}
const c=$("#choices");c.innerHTML="";os.forEach(o=>{let b=document.createElement("button");b.textContent=o.label;b.onclick=()=>answer(o.x);c.appendChild(b)});stats();clock()}
function update(ok,to=false){const s=state.get(cur.w);if(ok){s.r++;s.w=Math.max(0,s.w-1);s.status=s.r>=4?"已掌握":s.r>=2?"已熟悉":"學習中";s.due=turn+(s.r>=4?14:s.r>=2?7:4)}else{s.w++;s.r=Math.max(0,s.r-1);s.status="待加強";s.due=turn+(s.w>=2?1:to?3:2)}persist()}
function reveal(msg){$("#speak").style.visibility="visible";$("#feedback").textContent=msg;$("#answer").textContent=cur.w+" "+cur.p+"｜"+cur.z;$("#sentence").innerHTML=cur.e.replace(new RegExp("("+cur.w+")","ig"),"<strong>$1</strong>");$("#translation").textContent=cur.t;$("#example").style.display="block";$("#next").style.display="block"}
function answer(x){if(locked)return;locked=true;clearInterval(timer);[...$("#choices").children].forEach(b=>b.disabled=true);if(x.w===cur.w){combo++;let bonus=Math.round(left*10);score+=100+bonus+(combo-1)*20;update(true);$(".card").classList.remove("wrongflash");$(".card").classList.add("rightflash");setTimeout(()=>$(".card").classList.remove("rightflash"),500);reveal("答對！速度加分 +"+bonus+(combo>=3?"・"+combo+" 連擊":""))}else{combo=0;update(false);$(".card").classList.remove("rightflash");$(".card").classList.add("wrongflash");setTimeout(()=>$(".card").classList.remove("wrongflash"),450);reveal("答錯。正確答案："+cur.w+"｜"+cur.z)}stats()}
function fail(to){if(locked)return;locked=true;clearInterval(timer);combo=0;update(false,to);[...$("#choices").children].forEach(b=>b.disabled=true);reveal("時間到。正確答案："+cur.w+"｜"+cur.z);stats()}
const welcome=$("#welcome");if(!localStorage.getItem("djhs2000-welcome-seen"))welcome.style.display="flex";$("#dismissWelcome").onclick=()=>{localStorage.setItem("djhs2000-welcome-seen","1");welcome.style.display="none"};document.querySelectorAll(".trackbtn").forEach(b=>{b.addEventListener("click",e=>{e.preventDefault();setTrack(b.dataset.track)})});document.querySelectorAll(".trackbtn").forEach(b=>b.classList.toggle("active",b.dataset.track===track));const tn={auto:"自動適性｜依目前答題表現動態調整題池；答得穩會逐步加入較難字。",core:"基礎 1200｜1,200 字打底題池，適合先建立基本字彙量。",full:"完整 2000｜2,055 筆國中常用候選字詞，適合全面練習。",gept:"GEPT 初級｜目前以較常用的 1,600 字作進階練習，官方初級標記持續核對。"};$("#tracknote").textContent=tn[track];$("#next").onclick=show;$("#speak").onclick=()=>{if(!locked&&mode!=="en"&&mode!=="listen")return;speak(cur.w)};$("#speakSentence").onclick=()=>speak(cur.e);$("#shadowWord").onclick=()=>shadow(cur.w,false);$("#shadowSentence").onclick=()=>shadow(cur.e,true);if(!SR){$("#shadowWord").title="此瀏覽器不支援語音辨識";$("#shadowSentence").title="此瀏覽器不支援語音辨識"}$("#reset").onclick=()=>{if(confirm("確定要清除這台裝置的學習進度嗎？")){localStorage.removeItem("djhs2000");location.reload()}};show()})();