window.WORDS=[
{w:"able",p:"adj.",z:"有能力的",e:"She is able to solve the problem.",t:"她有能力解決這個問題。"},
{w:"accept",p:"v.",z:"接受",e:"Please accept my apology.",t:"請接受我的道歉。"},
{w:"accident",p:"n.",z:"意外；事故",e:"He was hurt in a car accident.",t:"他在一場車禍中受傷。"},
{w:"active",p:"adj.",z:"活躍的；積極的",e:"She is active in school activities.",t:"她積極參與學校活動。"},
{w:"advice",p:"n.",z:"建議",e:"My teacher gave me useful advice.",t:"老師給了我有用的建議。"},
{w:"afraid",p:"adj.",z:"害怕的",e:"The little boy is afraid of dogs.",t:"那個小男孩怕狗。"},
{w:"agree",p:"v.",z:"同意",e:"I agree with your idea.",t:"我同意你的想法。"},
{w:"airport",p:"n.",z:"機場",e:"We arrived at the airport early.",t:"我們很早就抵達機場。"},
{w:"allow",p:"v.",z:"允許",e:"My parents allow me to ride a bike.",t:"我的父母允許我騎腳踏車。"},
{w:"ancient",p:"adj.",z:"古代的；古老的",e:"We visited an ancient temple.",t:"我們參觀了一座古老的寺廟。"},
{w:"angry",p:"adj.",z:"生氣的",e:"Dad was angry about the broken window.",t:"爸爸對破掉的窗戶感到生氣。"},
{w:"arrive",p:"v.",z:"到達",e:"The train will arrive at six.",t:"火車將在六點抵達。"},
{w:"artist",p:"n.",z:"藝術家",e:"The artist painted a beautiful picture.",t:"那位藝術家畫了一幅美麗的畫。"},
{w:"avoid",p:"v.",z:"避免",e:"Try to avoid making the same mistake.",t:"試著避免犯相同的錯誤。"},
{w:"beautiful",p:"adj.",z:"美麗的",e:"The sunset is beautiful tonight.",t:"今晚的夕陽很美。"},
{w:"believe",p:"v.",z:"相信",e:"I believe you can do it.",t:"我相信你做得到。"},
{w:"borrow",p:"v.",z:"借入",e:"Can I borrow your pencil?",t:"我可以借你的鉛筆嗎？"},
{w:"brave",p:"adj.",z:"勇敢的",e:"The brave girl helped the child.",t:"那位勇敢的女孩幫助了小孩。"},
{w:"careful",p:"adj.",z:"小心的",e:"Be careful when you cross the street.",t:"過馬路時要小心。"},
{w:"choose",p:"v.",z:"選擇",e:"You can choose your favorite book.",t:"你可以選擇你最喜歡的書。"},
{w:"clever",p:"adj.",z:"聰明的",e:"That is a clever way to solve it.",t:"那是解決它的聰明方法。"},
{w:"collect",p:"v.",z:"收集",e:"I collect postcards from different countries.",t:"我收集不同國家的明信片。"},
{w:"compare",p:"v.",z:"比較",e:"Compare the two pictures carefully.",t:"仔細比較這兩張圖片。"},
{w:"confident",p:"adj.",z:"有自信的",e:"She feels confident before the test.",t:"她在考試前感到很有自信。"},
{w:"dangerous",p:"adj.",z:"危險的",e:"It is dangerous to play on the road.",t:"在馬路上玩很危險。"},
{w:"delicious",p:"adj.",z:"美味的",e:"The noodles are delicious.",t:"這些麵很好吃。"},
{w:"describe",p:"v.",z:"描述",e:"Can you describe the man?",t:"你能描述那名男子嗎？"},
{w:"discover",p:"v.",z:"發現",e:"They discovered a small cave.",t:"他們發現了一個小洞穴。"},
{w:"education",p:"n.",z:"教育",e:"Education can change our lives.",t:"教育可以改變我們的生活。"},
{w:"environment",p:"n.",z:"環境",e:"We should protect the environment.",t:"我們應該保護環境。"}
];