-- DJHS English 2000 leaderboard schema
-- Mirrors the initial production schema created in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.players (
  id uuid primary key default gen_random_uuid(),
  device_token uuid not null unique default gen_random_uuid(),
  nickname text not null check (char_length(trim(nickname)) between 1 and 20),
  xp integer not null default 0 check (xp >= 0),
  weekly_xp integer not null default 0 check (weekly_xp >= 0),
  mastered_words integer not null default 0 check (mastered_words >= 0),
  best_combo integer not null default 0 check (best_combo >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.learning_events (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  event_type text not null check (event_type in ('correct','mastered','review','listening','context')),
  word text not null check (char_length(word) between 1 and 80),
  xp integer not null default 0 check (xp between 0 and 50),
  created_at timestamptz not null default now()
);

create index if not exists players_xp_idx on public.players (xp desc);
create index if not exists players_weekly_xp_idx on public.players (weekly_xp desc);
create index if not exists learning_events_player_idx on public.learning_events (player_id);
create index if not exists learning_events_created_idx on public.learning_events (created_at desc);

create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;
drop trigger if exists players_set_updated_at on public.players;
create trigger players_set_updated_at before update on public.players
for each row execute function public.set_updated_at();

alter table public.players enable row level security;
alter table public.learning_events enable row level security;

drop policy if exists "Leaderboard is publicly readable" on public.players;
create policy "Leaderboard is publicly readable"
on public.players for select to anon, authenticated using (true);

revoke insert, update, delete on public.players from anon, authenticated;
revoke all on public.learning_events from anon, authenticated;
grant select on public.players to anon, authenticated;
